[package]
name = "twothousand-forty-eight"
version = "0.1.0"
edition = "2021"
authors = ["jonnelafin <elias.eskelinen@pm.me>"]
license = "MIT"
keywords = ["2048", "game"]
description = "a basic engine and move validator for the game 2048"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
sha2 = {version = "0.9.8", optional = true}

[features]
default = ["history_hash"]
history_hash = ["sha2"]