[package]
name = "twothousand-forty-eight"
version = "0.1.0"
edition = "2021"
authors = ["jonnelafin <elias.eskelinen@pm.me>"]
license = "MIT"
keywords = ["2048", "game"]
description = "a basic engine and move validator for the game 2048"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = {version = "0.9.8", optional = true}
wasm-bindgen = {version = "0.2.78", optional = true}
serde = {version = "1.0.130", optional = true, features = ["derive"]}
serde_json = {version = "1.0.72", optional = true}
getrandom = { version = "0.2", features = ["js"], optional = true }
rand = {version = "0.8.4", optional = true}

[features]
default = ["history_hash", "tile_id", "wasm"]
history_hash = ["sha2"]
wasm = ["wasm-bindgen", "serde", "serde_json", "getrandom", "rand"]
tile_id = []