[package]
name = "twothousand-forty-eight"
version = "0.3.1"
edition = "2021"
authors = ["xypine <elias.eskelinen@pm.me>"]
license = "MIT"
keywords = ["2048", "game"]
description = "a basic engine and move validator for the game 2048"
repository = "https://github.com/hallabois/twothousand-forty-eight"
documentation = "https://hallabois.github.io/twothousand-forty-eight/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = {version = "0.9.8", optional = true}
wasm-bindgen = {version = "0.2.78", optional = true}
serde = {version = "1.0.130", optional = true, features = ["derive"]}
serde_json = {version = "1.0.72", optional = true}
getrandom = { version = "0.2", features = ["js"], optional = true }
rand = {version = "0.8.4", optional = true}

[features]
default = ["history_hash", "tile_id", "wasm", "add_random"]
history_hash = ["sha2"]
serde_derive = ["serde", "serde_json"]
wasm = ["serde_derive", "wasm-bindgen", "getrandom", "rand"]
add_random = ["getrandom", "rand"]
tile_id = []