[package]
name = "twothousand-forty-eight"
version = "0.16.1"
edition = "2021"
authors = ["xypine <elias.eskelinen@pm.me>"]
license = "MIT"
keywords = ["2048", "game"]
description = "a basic engine and move validator for the game 2048"
repository = "https://github.com/hallabois/twothousand-forty-eight"
documentation = "https://docs.rs/twothousand_forty_eight"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = {version = "0.9.8", optional = true}
wasm-bindgen = {version = "0.2.78", optional = true}
serde = {version = "1.0.130", optional = true, features = ["derive"]}
serde_json = {version = "1.0.72", optional = true}
thiserror = "1.0.37"

[dev-dependencies]
regex = "1.5"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "validator"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "board"
harness = false

[features]
default = ["history_hash", "serde_derive"]
all = ["history_hash", "serde_derive", "wasm"]

history_hash = ["sha2"]
serde_derive = ["serde", "serde_json"]
wasm = ["serde_derive", "wasm-bindgen"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
opt-level = 3 # All optimizations
